const lyrics = [[0,"Waiting in a car"],[5,"Waiting for a ride in the dark"],[10,"The night city grows"],[15,"Look and see her eyes, they glow"],[20,"Longing for a time"],[25,"The city is my church"],[30,"And I am free tonight"],[36,"Running through the lights"],[42,"Midnight city"],[48,"Midnight city"],[54,"The city is my church"],[60,"I am free tonight"],[67,"Waiting in a car"]];
const PUBLIC_SPOTIFY_CLIENT_ID = "9d9c85cb8a9d4134adc57e6975e90c1c";
let elapsed = 42;
let accessToken = sessionStorage.getItem("pulseAccessToken");
const savedSettings = JSON.parse(localStorage.getItem("pulseSettings") || "{}");
const lyricWindow = document.querySelector("#lyricsWindow");
function renderLyricNodes(){lyricWindow.replaceChildren(...lyrics.map(([,text])=>{const line=document.createElement("p");line.className="lyric-line";line.textContent=text;return line;}));}
renderLyricNodes();
let lines=[...document.querySelectorAll(".lyric-line")];
function formatTime(seconds){return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,"0")}`;}
function render(){const active=lyrics.reduce((index,[time],i)=>elapsed>=time?i:index,0);lines.forEach((line,i)=>line.className=`lyric-line ${i<active?"passed":""} ${i===active?"active":""}`);document.querySelector("#currentTime").textContent=formatTime(elapsed);document.querySelector("#progressBar").style.width=`${Math.min(100,elapsed/243*100)}%`;if(lines[active]&&active>1)lyricWindow.scrollTo({top:Math.max(0,lines[active].offsetTop-110),behavior:"smooth"});}
render();setInterval(()=>{elapsed=elapsed>=243?0:elapsed+1;render();},1000);
document.querySelector("#favoriteButton").addEventListener("click",e=>{e.currentTarget.textContent=e.currentTarget.textContent==="♡"?"♥":"♡";});
document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-mode]").forEach(item=>item.classList.remove("active"));button.classList.add("active");lyricWindow.style.overflowY=button.dataset.mode==="scroll"?"auto":"hidden";}));
document.querySelector("#fullscreenButton").addEventListener("click",()=>document.documentElement.requestFullscreen?.());
const dialog=document.querySelector("#settingsDialog");document.querySelector("#settingsButton").addEventListener("click",()=>dialog.showModal());document.querySelector("#closeSettings").addEventListener("click",()=>dialog.close());
document.querySelector("#saveSettings").addEventListener("click",()=>{localStorage.setItem("pulseSettings",JSON.stringify({lyricsApi:document.querySelector("#lyricsApi").value.trim()}));document.querySelector("#connectionLabel").textContent="CONFIGURED";dialog.close();});
async function makeChallenge(){const verifier=crypto.randomUUID().replaceAll("-","");const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");sessionStorage.setItem("pulseVerifier",verifier);return challenge;}
async function spotifyLogin(clientId){const challenge=await makeChallenge();const redirect=`${location.origin}${location.pathname}`;const params=new URLSearchParams({client_id:clientId,response_type:"code",redirect_uri:redirect,code_challenge_method:"S256",code_challenge:challenge,scope:"user-read-currently-playing user-read-playback-state"});location.href=`https://accounts.spotify.com/authorize?${params}`;}
async function exchangeCode(clientId,code){const body=new URLSearchParams({client_id:clientId,grant_type:"authorization_code",code,redirect_uri:`${location.origin}${location.pathname}`,code_verifier:sessionStorage.getItem("pulseVerifier")});const response=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!response.ok)throw new Error("Spotify token exchange failed");const token=await response.json();sessionStorage.setItem("pulseAccessToken",token.access_token);sessionStorage.removeItem("pulseVerifier");return token.access_token;}
async function loadLyrics(title,artist){if(!savedSettings.lyricsApi)return;const response=await fetch(`${savedSettings.lyricsApi}?${new URLSearchParams({title,artist})}`);if(!response.ok)throw new Error("Lyrics API request failed");const result=await response.json();if(!Array.isArray(result))return;lyrics.splice(0,lyrics.length,...result.map(line=>[line.time,line.text]));renderLyricNodes();lines=[...document.querySelectorAll(".lyric-line")];render();}
function disconnectSpotify(){accessToken=null;sessionStorage.removeItem("pulseAccessToken");sessionStorage.removeItem("pulseVerifier");document.querySelector("#connectionLabel").textContent="DEMO MODE";document.querySelector("#connectButton").innerHTML="<span>♫</span> Подключить Spotify";}
async function refreshCurrentTrack(){if(!accessToken)return;const response=await fetch("https://api.spotify.com/v1/me/player",{headers:{Authorization:`Bearer ${accessToken}`}});if(response.status===204)return;if(response.status===401){disconnectSpotify();return;}if(!response.ok)throw new Error("Spotify player request failed");const data=await response.json();if(!data.item)return;document.querySelector("#trackTitle").textContent=data.item.name;document.querySelector("#trackArtist").textContent=data.item.artists.map(artist=>artist.name).join(", ");elapsed=Math.floor((data.progress_ms||0)/1000);document.querySelector("#totalTime").textContent=formatTime(Math.floor(data.item.duration_ms/1000));const art=data.item.album?.images?.[0]?.url;if(art)document.querySelector("#albumArt").style.background=`url("${art}") center/cover`;render();loadLyrics(data.item.name,data.item.artists[0]?.name).catch(console.error);}
document.querySelector("#disconnectButton").addEventListener("click",()=>{disconnectSpotify();dialog.close();});
document.querySelector("#connectButton").addEventListener("click",async()=>{if(!accessToken){await spotifyLogin(PUBLIC_SPOTIFY_CLIENT_ID);return;}document.querySelector("#connectionLabel").textContent="SPOTIFY READY";document.querySelector("#connectButton").innerHTML="<span>✓</span> Spotify подключён";});
const callbackCode=new URLSearchParams(location.search).get("code");if(callbackCode)exchangeCode(PUBLIC_SPOTIFY_CLIENT_ID,callbackCode).then(token=>{accessToken=token;history.replaceState({},"",location.pathname);refreshCurrentTrack();}).catch(console.error);
if(accessToken){document.querySelector("#connectionLabel").textContent="SPOTIFY READY";document.querySelector("#connectButton").innerHTML="<span>✓</span> Spotify подключён";refreshCurrentTrack().catch(console.error);}
setInterval(()=>refreshCurrentTrack().catch(console.error),10000);
